### ISSUE TITLE
rails 4?

### ISSUE THREAD

**Issue by eljojo** [camarapublica/camarapublica#2]
¿qué les parece si actualizo el sistema a rails4 rc1?

en el trabajo lo estoy usando y está bien bueno.

**Comment by eljojo** [comment]
cc @drphaser

**Comment by explodi** [comment]
enserio? yo no lo he probado todavía. hagamoslo!

**Comment by eljojo** [comment]
Yup, comencé a trabajar en el asunto.
Creé el branch [rails4](https://github.com/camarapublica/camarapublica/compare/rails4).

Hay hartas cosas que hacer todavía, pero va bien la cosa.
