### ISSUE TITLE
sucker punch

### ISSUE THREAD

**Issue by eljojo** [camarapublica/camarapublica#3]
As we'll want the app to run on heroku at some point, maybe it would be good to process the queue with [Sucker Punch](https://github.com/brandonhilkert/sucker_punch) rather than delayed_job.

I've never used, but the main idea is that it uses the same ruby process than the rails server, so we don't have to pay for the extra heroku worker.

I don't really know how good it works, but I guess is worth a shot.

**Comment by explodi** [comment]
right now it works in heroku with delayed job. actually that was the gem originally suported with heroku´s workers.

i havent tried other ways to delay jobs but it seems [resque](https://github.com/defunkt/resque) is also a very good alternative (but needs redis)

**Comment by eljojo** [comment]
right, that's true, but in order for it to work, we need to create a heroku worker (which costs money), right?
I mean, executing `heroku ps:scale worker=1`.

At work I use Sidekiq, which is better than Resque in terms of memory usage (all workers share the memory, so 25 workers = same memory as 1 rails app).

**Comment by explodi** [comment]
si pero yo lo estoy pagando mientras no hay donaciones (y esta corriendo)

On May 18, 2013, at 12:21 PM, "José Tomás Albornoz" <
notifications@github.com> wrote:

right, that's true, but in order for it to work, we need to create a heroku
worker (which costs money), right?
I mean, executing heroku ps:scale worker=1.

—
Reply to this email directly or view it on
GitHubhttps://github.com/camarapublica/camarapublica/issues/3#issuecomment-18103801
.

**Comment by explodi** [comment]
por ahora delayed_job está funcionando bien. propongo que reabramos este ticket cuando queramos optimizar la app. pero por ahora está configurado con 2 dynos y 1 worker que deberían soportar 1000+ requests/minuto y la info del parlamento se está actualizando cada hora :)
